[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts"]

#foundry-fund-me\lib\chainlink-brownie-contracts\contracts\src\v0.8\shared\interfaces\AggregatorV3Interface.sol

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
